### ISSUE TITLE
有错误 

### ISSUE THREAD

**Issue by YY-8885** [xiutai/boom#1]
Traceback (most recent call last):
  File "boom.py", line 39, in <module>
UnicodeDecodeError: 'gbk' codec can't decode byte 0x82 in position 1042183: illegal multibyte sequence
[4220] Failed to execute script 'boom' due to unhandled exception!

这个是什么错误？

**Comment by YY-8885** [comment]
找到问题了，我的txt是utf-8编码，无法识别，只能识别ANSI编码
作者请修复下

**Comment by YY-8885** [comment]
还有个问题，IP段过多或者密码字典过多，占用内存太多，也请作者修复一下，感谢

**Comment by YY-8885** [comment]
大量占用内存应该是日志导致，要是能把日志写入文本应该就不大量占用内存

**Comment by xiutai** [comment]
> 大量占用内存应该是日志导致，要是能把日志写入文本应该就不大量占用内存

其实我写这个工具的初衷是针对内网或者指定指定范围进行爆破，并不适用大面积盲爆。虽然大面积盲爆也可以实现，但其实意义并不大，没什么好货的。

**Comment by xiutai** [comment]
> Traceback (most recent call last): File "boom.py", line 39, in UnicodeDecodeError: 'gbk' codec can't decode byte 0x82 in position 1042183: illegal multibyte sequence [4220] Failed to execute script 'boom' due to unhandled exception!
> 
> 这个是什么错误？

已经修复

**Comment by xiutai** [comment]
> 还有个问题，IP段过多或者密码字典过多，占用内存太多，也请作者修复一下，感谢

增加了日志保存方式，可以选择包存到内存或者文件中，也可以不保存日志

**Comment by YY-8885** [comment]
> > 还有个问题，IP段过多或者密码字典过多，占用内存太多，也请作者修复一下，感谢
> 
> 增加了日志保存方式，可以选择包存到内存或者文件中，也可以不保存日志

爆破模式好像是所有字典跑完一个IP再继续下一个IP，能不能让它混合模式

**Comment by YY-8885** [comment]
> > 还有个问题，IP段过多或者密码字典过多，占用内存太多，也请作者修复一下，感谢
> 
> 增加了日志保存方式，可以选择包存到内存或者文件中，也可以不保存日志

你好，今天测试了下，写入日志文件还是大量占用内存

**Comment by xiutai** [comment]
> > > 还有个问题，IP段过多或者密码字典过多，占用内存太多，也请作者修复一下，感谢
> 
> > 
> 
> > 增加了日志保存方式，可以选择包存到内存或者文件中，也可以不保存日志
> 
> 
> 
> 爆破模式好像是所有字典跑完一个IP再继续下一个IP，能不能让它混合模式

这个问题下次更新的话会改进

**Comment by xiutai** [comment]
> > > 还有个问题，IP段过多或者密码字典过多，占用内存太多，也请作者修复一下，感谢
> 
> > 
> 
> > 增加了日志保存方式，可以选择包存到内存或者文件中，也可以不保存日志
> 
> 
> 
> 你好，今天测试了下，写入日志文件还是大量占用内存

试试不记录日志呢？如果占用内存太大的话可以尝试把线程改小点。

**Comment by YY-8885** [comment]
> > > > 还有个问题，IP段过多或者密码字典过多，占用内存太多，也请作者修复一下，感谢
> > 
> > 
> > > 
> > 
> > 
> > > 增加了日志保存方式，可以选择包存到内存或者文件中，也可以不保存日志
> > 
> > 
> > 你好，今天测试了下，写入日志文件还是大量占用内存
> 
> 试试不记录日志呢？如果占用内存太大的话可以尝试把线程改小点。

![1](https://github.com/xiutai/boom/assets/154723865/002f6b5a-3a9c-4dd7-8f83-d09634ea503b)

刚刚测试了下，不管是Linux还是WINDOWS，写入和不写入日志都是大量占用虚拟内存
